### ISSUE TITLE
Resources$NotFoundException when run source without any modification

### ISSUE THREAD

**Issue by JVeverGiveUp** [sky-map-team/stardroid#172]
I tried to import project to Android Studio 2.3.3 and still using default config of project (without modification of any string). When I run fatal error happens, I also tried to remove all of other languages resource but no luck. Any suggestion for me.

W/Stardroid.AbstractLayer: Renderer not set - aborting: NewConstellationsLayer
com.google.android.stardroid W/ResourceType: For resource 0x7f0701fd, entry index(509) is beyond type entryCount(508)
com.google.android.stardroid W/ResourceType: Failure getting entry for 0x7f0701fd (t=6 e=509) (error -75)
com.google.android.stardroid E/AndroidRuntime_3_crash: crash in the same process: pool-3-thread-3
                                                                                      android.content.res.Resources$NotFoundException: String resource ID #0x7f0701fd
                                                                                          at android.content.res.Resources.getText(Resources.java:286)
                                                                                          at android.content.res.Resources.getString(Resources.java:372)
                                                                                          at com.google.android.stardroid.source.proto.ProtobufAstronomicalSource.getLabels(ProtobufAstronomicalSource.java:111)
                                                                                          at com.google.android.stardroid.layers.AbstractSourceLayer.initialize(AbstractSourceLayer.java:74)
                                                                                          at com.google.android.stardroid.layers.AbstractFileBasedLayer.access$201(AbstractFileBasedLayer.java:46)
                                                                                          at com.google.android.stardroid.layers.AbstractFileBasedLayer$1.run(AbstractFileBasedLayer.java:65)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                          at java.lang.Thread.run(Thread.java:818)

**Comment by androidqasim** [comment]
i am also facing the same issue. did you resolve it?

**Comment by androidqasim** [comment]
i got the solution.. comment for loop and pass hard coded string and rebuild it. it will work

**Comment by jaydeetay** [comment]
I think one problem is that the datafiles are out of sync with the code.  We have a weird build that we created 10 years ago and really needs throwing out.  If any strings are added or removed the datafiles need to be regenerated.
