### ISSUE TITLE
App crashing on Runtime

### ISSUE THREAD

**Issue by aayushsingla** [sky-map-team/stardroid#253]
**Summary:** 
App crashes on runtime when built from current master

**Steps to reproduce:** 
just launch the app

**Expected behavior:** 
app shall not crash

**Observed behavior:** 
app crashes
**Device and Android version:** 
Redmi note 4 running MIUI Global 10.2 

**Logcat Error** 
```
 10:41:34.640 22309-22328/com.google.android.stardroid E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: com.google.android.stardroid, PID: 22309
    android.content.res.Resources$NotFoundException: String resource ID #0x7f0d0214
        at android.content.res.Resources.getText(Resources.java:347)
        at android.content.res.MiuiResources.getText(MiuiResources.java:97)
        at android.content.res.Resources.getString(Resources.java:393)
        at com.google.android.stardroid.source.proto.ProtobufAstronomicalSource.getLabels(ProtobufAstronomicalSource.java:111)
        at com.google.android.stardroid.layers.AbstractSourceLayer.initialize(AbstractSourceLayer.java:74)
        at com.google.android.stardroid.layers.AbstractFileBasedLayer.access$201(AbstractFileBasedLayer.java:46)
        at com.google.android.stardroid.layers.AbstractFileBasedLayer$1.run(AbstractFileBasedLayer.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)

```

**Comment by utkarsh530** [comment]
@aayushsingla I think you forgot to run ``./build_skymap.sh`` before running the app. https://github.com/sky-map-team/stardroid/tree/master/tools

**Comment by jaydeetay** [comment]
Yes, that's most likely it.  The ids get copied into a data file and
various things can cause the ids to be regenerated - adding a new message,
new version of the sdk etc.  It's safest to just regenerate using that
script, clunky though it is.
