### ISSUE TITLE
App crashing due to ResourceNotFoundException

### ISSUE THREAD

**Issue by tavishjain** [sky-map-team/stardroid#260]
**Summary:** 

The app crashes on startup

**Steps to reproduce:** 

Simply open the application on Android Pie, the app will crash

**Expected behavior:** 

I expected the application to run

**Device and Android version:** 

Device - Pixel 2XL
Android - Pie (Android 9)

**Logs:** 
```2019-03-30 22:22:46.830 4691-4714/com.google.android.stardroid E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: com.google.android.stardroid, PID: 4691
    android.content.res.Resources$NotFoundException: String resource ID #0x7f0d0214
        at android.content.res.Resources.getText(Resources.java:348)
        at android.content.res.Resources.getString(Resources.java:441)
        at com.google.android.stardroid.source.proto.ProtobufAstronomicalSource.getLabels(ProtobufAstronomicalSource.java:111)
        at com.google.android.stardroid.layers.AbstractSourceLayer.initialize(AbstractSourceLayer.java:74)
        at com.google.android.stardroid.layers.AbstractFileBasedLayer.access$201(AbstractFileBasedLayer.java:46)
        at com.google.android.stardroid.layers.AbstractFileBasedLayer$1.run(AbstractFileBasedLayer.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)```

**Comment by jaydeetay** [comment]
You almost certainly need to run the script mentioned in /tools.  We have a pretty awful build process I'm afraid.

**Comment by tavishjain** [comment]
Sorry @jaydeetay but which script are you referring to ?

**Comment by jaydeetay** [comment]
The build_skymap.sh script mentioned here:
https://github.com/sky-map-team/stardroid/blob/master/tools/README.md

The core problem we've always had is that the star names are embedded in
datafiles. We don't really want to add versions of the data files for each
locale, so instead we process them to refer to entities in strings.xml.
The mapping between the two needs to be regenerated frequently otherwise
mismatches or crashes occur. I'm still trying to figure out a better way to
do this.
